# Generated by Django 4.1 on 2024-01-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.FloatField()),
                ("stock", models.IntegerField(default=0, null=True)),
                ("moq", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="products_pics"),
                ),
                ("discount_percent", models.IntegerField(default=0)),
            ],
        ),
    ]
